# Generated by Django 5.0.7 on 2024-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondInfo',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='代码')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('names', models.TextField(verbose_name='搜索')),
                ('date', models.DateField(verbose_name='日期')),
                ('source', models.IntegerField(choices=[(1, '东方财富'), (2, '同花顺')], default=1, verbose_name='平台')),
            ],
            options={
                'db_table': 'bond_info',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='代码')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('names', models.TextField(verbose_name='搜索')),
                ('date', models.DateField(verbose_name='日期')),
                ('source', models.IntegerField(choices=[(1, '东方财富'), (2, '同花顺')], default=1, verbose_name='平台')),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
        migrations.CreateModel(
            name='TopicInfo',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='代码')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('names', models.TextField(verbose_name='搜索')),
                ('date', models.DateField(verbose_name='日期')),
                ('source', models.IntegerField(choices=[(1, '东方财富'), (2, '同花顺')], default=1, verbose_name='平台')),
            ],
            options={
                'db_table': 'topic_info',
            },
        ),
        migrations.CreateModel(
            name='StockBond',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.CharField(max_length=10, verbose_name='债券代码')),
                ('bond', models.CharField(max_length=10, verbose_name='债券名称')),
                ('date', models.DateField(verbose_name='关联日期')),
            ],
            options={
                'db_table': 'stock_bond',
                'unique_together': {('stock', 'bond')},
            },
        ),
        migrations.CreateModel(
            name='StockMarketDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='代码')),
                ('date', models.DateField(verbose_name='日期')),
                ('pe', models.FloatField(verbose_name='市盈率')),
                ('pb', models.FloatField(verbose_name='市净率')),
                ('market_cap', models.FloatField(verbose_name='总市值')),
                ('float_cap', models.FloatField(verbose_name='流通市值')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('average', models.FloatField(verbose_name='日均价')),
                ('close_1', models.FloatField(null=True, verbose_name='前收盘价')),
                ('volume', models.FloatField(verbose_name='成交量')),
                ('turnover', models.FloatField(verbose_name='成交额')),
                ('change', models.FloatField(verbose_name='涨幅')),
                ('change_rate', models.FloatField(verbose_name='涨幅')),
                ('change_rate_5', models.FloatField(verbose_name='5日涨幅')),
                ('amplitude', models.FloatField(verbose_name='振幅')),
                ('volume_rate', models.FloatField(verbose_name='量比')),
                ('turnover_rate', models.FloatField(verbose_name='换手率')),
                ('money_ma', models.FloatField(db_column='m_ma', verbose_name='主力资金')),
                ('money_rate_ma', models.FloatField(db_column='mr_ma', verbose_name='主力资金比例')),
                ('money_sb', models.FloatField(db_column='m_sb', verbose_name='超大单资金')),
                ('money_rate_sb', models.FloatField(db_column='mr_sb', verbose_name='超大单资金比例')),
                ('money_b', models.FloatField(db_column='m_b', verbose_name='大单净流入')),
                ('money_rate_b', models.FloatField(db_column='mr_b', verbose_name='大单净流入比例')),
                ('money_m', models.FloatField(db_column='m_m', verbose_name='中单资金')),
                ('money_rate_m', models.FloatField(db_column='mr_n', verbose_name='中单资金比例')),
                ('money_s', models.FloatField(db_column='m_s', verbose_name='小单资金')),
                ('money_rate_s', models.FloatField(db_column='mr_s', verbose_name='小单资金比例')),
                ('indi_vol', models.CharField(choices=[('d1', '日线量变'), ('m30', '30分钟线量变')], db_column='i_vol', default='d1', max_length=4, verbose_name='量变指标')),
            ],
            options={
                'db_table': 'stock_market_day',
                'unique_together': {('code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockTopic',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.CharField(max_length=10, verbose_name='题材代码')),
                ('topic', models.CharField(max_length=10, verbose_name='题材名称')),
                ('date', models.DateField(verbose_name='关联日期')),
            ],
            options={
                'db_table': 'stock_topic',
                'unique_together': {('stock', 'topic')},
            },
        ),
    ]
